# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RasterGeocDependenceOne <- function(x) {
    .Call(`_geocomplexity_RasterGeocDependenceOne`, x)
}

RasterGeocDependence <- function(x, ni = 9L, nw = 9L) {
    .Call(`_geocomplexity_RasterGeocDependence`, x, ni, nw)
}

