# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RasterGeocSpatialDependenceOne <- function(x) {
    .Call(`_geocomplexity_RasterGeocSpatialDependenceOne`, x)
}

RasterGeocSpatialDependence <- function(x, ni = 9L, nw = 9L) {
    .Call(`_geocomplexity_RasterGeocSpatialDependence`, x, ni, nw)
}

