# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SelectSortedBW <- function(dist_mat, start_idx, end_idx) {
    .Call(`_geocomplexity_SelectSortedBW`, dist_mat, start_idx, end_idx)
}

GeoCD_SWM <- function(X, gcs, wt, style) {
    .Call(`_geocomplexity_GeoCD_SWM`, X, gcs, wt, style)
}

GeoCS_SWM <- function(x, wt, style) {
    .Call(`_geocomplexity_GeoCS_SWM`, x, wt, style)
}

GeoCGWRFit <- function(y, X, gcs, Gdist, bw = 0, knn = 0, adaptive = FALSE, alpha = 0.05, kernel = "gaussian") {
    .Call(`_geocomplexity_GeoCGWRFit`, y, X, gcs, Gdist, bw, knn, adaptive, alpha, kernel)
}

GeoCGWR <- function(y, X, gcs, Gdist, bw = 0, knn = 0, adaptive = FALSE, alpha = 0.01, kernel = "gaussian") {
    .Call(`_geocomplexity_GeoCGWR`, y, X, gcs, Gdist, bw, knn, adaptive, alpha, kernel)
}

InforEntropy <- function(x) {
    .Call(`_geocomplexity_InforEntropy`, x)
}

spatial_variance <- function(x, wt) {
    .Call(`_geocomplexity_spatial_variance`, x, wt)
}

MI_vec <- function(x, W, alternative = "greater", symmetrize = FALSE) {
    .Call(`_geocomplexity_MI_vec`, x, W, alternative, symmetrize)
}

print_global_moranI <- function(df) {
    .Call(`_geocomplexity_print_global_moranI`, df)
}

RasterGeoCMoranOne <- function(x, ni = 9L, nw = 9L) {
    .Call(`_geocomplexity_RasterGeoCMoranOne`, x, ni, nw)
}

RasterGeoCMoran <- function(x, ni = 9L, nw = 9L) {
    .Call(`_geocomplexity_RasterGeoCMoran`, x, ni, nw)
}

RasterGeoCSSH <- function(x, iw, w, method) {
    .Call(`_geocomplexity_RasterGeoCSSH`, x, iw, w, method)
}

RasterGeoCSimilarity <- function(x, iw, w, similarity, method) {
    .Call(`_geocomplexity_RasterGeoCSimilarity`, x, iw, w, similarity, method)
}

BasicGWRFit <- function(y, X, Gdist, bw = 0, knn = 0, adaptive = FALSE, kernel = "gaussian") {
    .Call(`_geocomplexity_BasicGWRFit`, y, X, Gdist, bw, knn, adaptive, kernel)
}

SGWRFit <- function(y, X, Gdist, bw = 0, knn = 0, adaptive = FALSE, alpha = 0.05, kernel = "gaussian") {
    .Call(`_geocomplexity_SGWRFit`, y, X, Gdist, bw, knn, adaptive, alpha, kernel)
}

SGWRSel <- function(bws, knns, alpha, y, X, Gdist, adaptive = FALSE, criterion = "RMSE", kernel = "gaussian") {
    .Call(`_geocomplexity_SGWRSel`, bws, knns, alpha, y, X, Gdist, adaptive, criterion, kernel)
}

VectorGeoCMoran <- function(x, wt) {
    .Call(`_geocomplexity_VectorGeoCMoran`, x, wt)
}

VectorGeoCSSH <- function(xobs, wt, method) {
    .Call(`_geocomplexity_VectorGeoCSSH`, xobs, wt, method)
}

VectorGeoCSimilarity <- function(xobs, wt, similarity, method) {
    .Call(`_geocomplexity_VectorGeoCSimilarity`, xobs, wt, similarity, method)
}

